"""create plant table

Revision ID: 33da00b39d40
Revises: 
Create Date: 2025-09-05 04:30:56.209477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33da00b39d40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('planting_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timeline_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=100), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timeline_event')
    op.drop_table('plant')
    # ### end Alembic commands ###
